### PR TITLE
Release data moved to the k/sig-release repo

### PR DESCRIPTION
**Pull request by idvoretskyi**
Ref: https://github.com/kubernetes/sig-release/pull/46

Do not merge before merging https://github.com/kubernetes/sig-release/pull/46.

### CODE REVIEW

**Comment by idvoretskyi** [comment]
cc @jdumars @stp-ip @calebamiles @grodrigues3 @spiffxp

**Comment by enisoc** [comment]
/hold
This is going to break the "release team" link in our blog post:

http://blog.kubernetes.io/2017/12/kubernetes-19-workloads-expanded-ecosystem.html

**Comment by idvoretskyi** [comment]
@enisoc agree, thanks.

Will update with the redirect link.

**Comment by idvoretskyi** [comment]
Closed as #533 fixed this.

**Pull request closed without merging**
