### PR TITLE
add federation content

### PR DESCRIPTION
**Pull request by radhikapc**
Source https://docs.google.com/spreadsheets/d/18V_8YvqemC96W17O_3WZ6H_kS7r77NAI9FqUHAM2MS0/edit#gid=0

### CODE REVIEW

**Comment by radhikapc** [comment]
@quinton-hoole @nikhiljindal @deepak-vij

**Comment by nikhiljindal** [comment]
Plz remove apps/v1beta1. We weren't able to get that in 1.8.

Quinton is the best person to lgtm

I will lgtm for now so that we have something and can improve in next PR.
Thx.

**Pull request merged**
