### PR TITLE
[Federation] Add feature gates and lack of upgrade tests to the known issues section.

### PR DESCRIPTION
**Pull request by madhusudancs**
cc @kubernetes/sig-federation @matchstick @nikhiljindal @roberthbailey

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM, thx!

**Comment by spiffxp** [comment]
@madhusudancs is there an issue number you can link to for this? and/or link that issue to the [v1.5.0 known issues accumulator issue](https://github.com/kubernetes/kubernetes/issues/37134)?   everything else in the known issues section links to an issue users can look to for future progress

**Comment by madhusudancs** [comment]
@spiffxp there wasn't one. Created and added a link to it in the notes.

**Comment by spiffxp** [comment]
LGTM

**Pull request merged**
