### PR TITLE
release note for HPA

### PR DESCRIPTION
**Pull request by ymqytw**
cc: @pwittrock

### CODE REVIEW

**Comment by liggitt** [comment]
I really don't think we should call this a breaking change. I don't want to set the expectation that we will release note every change to a printer

**Comment by pwittrock** [comment]
@liggitt @ymqytw and I are out Monday / Tuesday.  I would you be willing to TAL at the release notes on Monday and make sure this doesn't come as a surprise to anyone?

**Comment by liggitt** [comment]
Sure

**Comment by pwittrock** [comment]
@liggitt Thanks!

**Pull request merged**
