### PR TITLE
update list of sigs with release notes

### PR DESCRIPTION
**Pull request by Bradamant3**
Cleaned up the list to check off sigs that are done with their contributions and also sigs for which release notes are not applicable.

### CODE REVIEW

**Comment by jdumars** [comment]
@Bradamant3 you can also take SIG-Azure off the list ~ the 1.8 items slipped

**Comment by jdumars** [comment]
@Bradamant3 and SIG-Cluster-Ops can be removed

**Comment by jdumars** [comment]
And Governance and On-Premise ~ also able to be removed

**Comment by Bradamant3** [comment]
Added per @jdumars, plus sig-contribex

**Pull request merged**
