### PR TITLE
Update release_team.md

### PR DESCRIPTION
**Pull request by zacharysarah**
👋 I'm adding myself as a shadow to Steve Perry, in prep for acting as the 1.9 docs lead.

### CODE REVIEW

**Comment by zacharysarah** [comment]
Out of curiosity, can someone point me to the script that's auto-assigning `size/*` labels? I'm curious to see how it's implemented. :bowtie:

**Comment by luxas** [comment]
cc @spxtr @fejta on the size Prow plugin.

**Comment by spiffxp** [comment]
@zacharysarah 
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/size/size.go#L167-L181

**Pull request merged**
