### PR TITLE
Create CONTRIBUTING.md

### LINKED ISSUE #588: Missing CONTRIBUTING.md file
All K8s subrepositories should have a CONTRIBUTING.md file, which at the minimum should point to https://github.com/kubernetes/community/blob/master/contributors/guide/README.md. Care should be taken that all information is in sync with the contributor guide.

Subrepositories may also have contributing guidelines specific to that repository. They should be explicitly documented and explained in the CONTRIBUTING.md

Ref:  https://github.com/kubernetes/community/issues/1832

### PR DESCRIPTION
**Pull request by RA489**
Adding Contribution Guideline.
fixes #588

### CODE REVIEW

**Comment by RA489** [comment]
@stp-ip do i need to update it from https://git.k8s.io or its good to go?

**Comment by stp-ip** [comment]
Let's update it to git.k8s.io as another approval is still necessary anyway aka we have some time.
Thank you.

**Comment by justaugustus** [comment]
Thanks for the PR, @ra489!
/lgtm

**Pull request merged**
