### PR TITLE
Updated release notes for rescheduler

### PR DESCRIPTION
**Pull request by piosz**
cc @calebamiles @idvoretskyi @enisoc

### CODE REVIEW

**Comment by piosz** [comment]
@ethernetdan

**Comment by piosz** [comment]
@idvoretskyi @davidopp I'm traveling for Kubecon today. Can you please apply my changes to the other doc?

**Comment by idvoretskyi** [comment]
@piosz sure, no problem.

**Comment by idvoretskyi** [comment]
Done.

Thank you, @piosz.

**Comment by piosz** [comment]
@idvoretskyi thanks a lot!

**Pull request closed without merging**
