### PR TITLE
Propose Dawn, Ihor, Andrew, Wojciech as Release Team for 1.7

### PR DESCRIPTION
**Pull request by grodrigues3**

### CODE REVIEW

**Comment by philips** [comment]
Hey I want to echo what @bgrant0607 said on the other PR. We should be having these sorts of discussions on kubernetes-dev and then ratify decisions in github.com/kubernetes/community. 

https://github.com/kubernetes/features/pull/249#issuecomment-294622799

**Comment by grodrigues3** [comment]
Closing in favor of a more public discussion

**Comment by grodrigues3** [comment]
Re-opened as per K8s-dev thread.  To be view, discussed, approved at 04/20 community meeting.

**Comment by grodrigues3** [comment]
@calebamiles thanks for doing that.  Today's meeting day :(

**Comment by grodrigues3** [comment]
Approved at 04/20 Community Meeting

Doc to be updated as additional release roles are filled (e.g Bug Lead, Testing Lead)

**Pull request merged**
