### PR TITLE
Location of proposals directory corrected.

### PR DESCRIPTION
**Pull request by CsatariGergely**

### CODE REVIEW

**Comment by philips** [comment]
LGTM, why isn't this merged? cc @erictune

**Comment by philips** [comment]
Gah, it is because of the CLA. @CsatariGergely you have to sign a CLA to do this change.

**Comment by idvoretskyi** [comment]
@CsatariGergely, yes, we are still waiting for CLA from @CsatariGergely.

**Comment by CsatariGergely** [comment]
@idvoretskyi, @philips: I'm discussing the CLA issue with @bgrant0607, @sarahnovotny, @aronchick and @monadic in mail.

**Comment by philips** [comment]
@CsatariGergely what is the conclusion of the CLA issue?

**Comment by philips** [comment]
This is fixed and this PR can be closed.

**Pull request closed without merging**
