### PR TITLE
Add k8s.io docs to ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by chenopis**
Add description for different types of documentation on kubernetes.io for new features.

### CODE REVIEW

**Comment by chenopis** [comment]
@dchen1107 PTAL

**Comment by chenopis** [comment]
My goal is just to remind people of the new types of documentation (Concepts, Tasks, Tutorials, Reference) that can/should be created for new features instead of dumping everything into a user guide, which was the old convention. @idvoretskyi Do you have a suggestion for where in the submission process this can be done? @dchen1107 Do you want to chime in?

**Comment by idvoretskyi** [comment]
@chenopis agree, it's needed. For the previous Kubernetes releases we've been working with the docs team (Jared, Devin) with the spreadsheet, maintained by me, where the features are listed - I will prepare one for 1.7 as well.

It's not an ideal solution (rather workaround), so we have to find the better and constant way how we may achieve this.

**Comment by chenopis** [comment]
Ok. I'm in the docs team w/ Jared and Devin, and I'm supposed to handle the docs process for 1.7. I created the spreadsheet already based on the one from 1.6 and just added you. Let me know if you want me to make you the owner of that.

**Comment by idvoretskyi** [comment]
The [spreadsheet](https://docs.google.com/spreadsheets/d/1IJSTd3MHorwUt8i492GQaKKuAFsZppauT4v1LJ91WHY/edit#gid=0) is used now.

**Pull request closed without merging**
