### PR TITLE
Add kubeadm to 'Themes' for 1.6

### PR DESCRIPTION
**Pull request by jbeda**
Signed-off-by: Joe Beda <joe.github@bedafamily.com>

### CODE REVIEW

**Comment by jbeda** [comment]
Beta seems like a big deal on the par of the other features at the top.

**Comment by luxas** [comment]
LGTM

It would be interesting to know if the whitespace fixes were generate by you or a machine though ;)

**Comment by jbeda** [comment]
Whitespace fixes were by my editor.  Let me recreate without those...

**Comment by idvoretskyi** [comment]
@jbeda good point, thank you!

**Pull request merged**
