### PR TITLE
made summary/description usage consistent.

### PR DESCRIPTION
**Pull request by sarahnovotny**

### CODE REVIEW

**Comment by mikebrow** [comment]
Looks good.  Just a nit.. I'd go ahead and delete the top section entirely so the users don't have to. Would do that by moving the “thanks" and "staging description" paragraphs do the "more advice:" text.. and change "more advice:" to "process notes:."

**Comment by idvoretskyi** [comment]
LGTM.

**Comment by philips** [comment]
@sarahnovotny merge conflict :/

**Comment by idvoretskyi** [comment]
@sarahnovotny can you take a look at the possible reason of the merge conflict? 

PR looks good, but we have to fix the issue before the merging.

**Pull request closed without merging**
